name: Push CI

on:
  push:
    branches:
      - '**'
      - '!develop'
      - '!main'

jobs:
  test:
    name: Push CI - Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # pnpm should be preinstalled before the setup-node action
      # https://github.com/actions/setup-node/issues/530#issuecomment-1169317505
      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
